name: Deploy API to Cloud Foundry

on: [push,workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: manifest.yml
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}

      - name: Apply Manifest File
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: https://api.ng.bluemix.net
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: v3-apply-manifest -f manifest.yml
        
      - name: Deploy to IBM Cloud Foundry
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: https://api.ng.bluemix.net
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: v3-push ${{ secrets.APP_NAME }} -b https://github.com/cloudfoundry/apt-buildpack.git -b https://github.com/cloudfoundry/python-buildpack.git
